### ISSUE TITLE
missing driverlib/timer.h

### ISSUE THREAD

**Issue by sori-bit** [taoyuan/Timers#1]
Hi,

When I want to run your example Ardiono IDE rises below error.
Where could I find driverlib/timer.h?

 ![image](https://user-images.githubusercontent.com/75795711/146742280-d8f722c4-9ac8-430a-bb84-393de53461a7.png)

**Comment by taoyuan** [comment]
It is mainly used in energia and `driverlib/timer.h` is here: https://github.com/energia/cc3200-core
